// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz3D_i6BMQ4FLTUIlt78DXzfww22kkuvg',
    appId: '1:929282214972:web:44c2192fa57ca81ce98739',
    messagingSenderId: '929282214972',
    projectId: 'hikingnl-25b7a',
    authDomain: 'hikingnl-25b7a.firebaseapp.com',
    storageBucket: 'hikingnl-25b7a.firebasestorage.app',
    measurementId: 'G-M84MJNGHF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr6C9smKeymduT6kk3ilaSQjJPuops-FI',
    appId: '1:929282214972:android:ba323217b6030b46e98739',
    messagingSenderId: '929282214972',
    projectId: 'hikingnl-25b7a',
    storageBucket: 'hikingnl-25b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHFDkqN4f9Tco482kk2a4W98Gh7KL0OQ',
    appId: '1:929282214972:ios:ff5cb7312756761ae98739',
    messagingSenderId: '929282214972',
    projectId: 'hikingnl-25b7a',
    storageBucket: 'hikingnl-25b7a.firebasestorage.app',
    iosBundleId: 'com.example.hikingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHFDkqN4f9Tco482kk2a4W98Gh7KL0OQ',
    appId: '1:929282214972:ios:ff5cb7312756761ae98739',
    messagingSenderId: '929282214972',
    projectId: 'hikingnl-25b7a',
    storageBucket: 'hikingnl-25b7a.firebasestorage.app',
    iosBundleId: 'com.example.hikingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz3D_i6BMQ4FLTUIlt78DXzfww22kkuvg',
    appId: '1:929282214972:web:27f95932d1d0ab50e98739',
    messagingSenderId: '929282214972',
    projectId: 'hikingnl-25b7a',
    authDomain: 'hikingnl-25b7a.firebaseapp.com',
    storageBucket: 'hikingnl-25b7a.firebasestorage.app',
    measurementId: 'G-NZ38SV9X0X',
  );
}
